#!/bin/bash
#
# NAME
#   log-atrest - check a log file and report if vessel was at rest.
#
# SYNOPSIS
#   log-atrest [logfile]
#   log-atrest -h
#
# DESCRIPTION
#   If the script is invoked with no arguments, then it will operate as
#   if it had been called with a single logfile argument set to the
#   value YYYYMMDD that represents the current day.
#
#   Exits with EXITVALUE = 0 if the log file indicates that the vessel
#   was at rest (i.e. did not navigate) on the day in question,
#   otherwise sets EXITVALUE = 1. The script prints "1" on STDOUT if at
#   rest, otherwise "0" (yes, I know - a trap for the unwary).
#
#   The following options are understood:
#
#   -h  print this documentation;
#
# AUTHOR
#   Paul Reeve <preeve@pdjr.eu>

. /usr/local/bin/log.defs

LOG_FILENAME=$( ${DATE} '+%Y%m%d' )

while  [ "${1}" != "" ] ; do
  case ${1} in
    -h)
      ${SED} -e '/^$/,$d' ${0}
      exit 0
      ;;
    *)
      LOG_FILENAME=${1}
      ;;
  esac
  shift
done

if [ ! -f "${LOGDIR}${LOG_FILENAME}" ] ;  then echo "log-atrest: cannot find logfile '${LOG_FILENAME}'" ; exit 9 ; fi

POSITIONS="$( ${LOGPOSITIONS} ${LOG_FILENAME} )"
POSITIONCOUNT=$( ${GREP} -c '^' <<< "${POSITIONS}" )

if [ ${POSITIONCOUNT} -eq 1 ] ; then
  echo "1"
  exit 0
else
  echo "0"
  exit 1
fi
