#!/bin/bash
#
# NAME
#   log-atrest - check a log file and report if vessel was at rest.
#
# SYNOPSIS
#   log-atrest [-v] [logfile]
#   log-atrest -h
#
# DESCRIPTION
#   If the script is invoked with no arguments, then it will operate as
#   if it had been called with a single logfile argument set to the
#   value YYYYMMDD that represents the current day.
#
#   Exits with EXITVALUE = 0 if the log file indicates that the vessel
#   was at rest (i.e. did not navigate) on the day in question,
#   otherwise sets EXITVALUE = 1.
#
#   The following options are understood:
#
#   -h  print this documentation;
#
#   -v  As well as setting EXITVALUE, print to standard out the value
#       "yes" if the vessel was at rest and "no" if it wasn't.
#
# AUTHOR
#   Paul Reeve <preeve@pdjr.eu>

source log.defs

LOG_FILENAME=$( ${DATE} '+Ymd' )

while  [ "${1}" != "" ] ; do
  case ${1} in
    -h)
      ${GREP} '^#' ${0}
      exit 0
      ;;
    -v)
      OPTION_VERBOSE=1
      ;;
    *)
      LOG_FILENAME=${1}
      ;;_
  esac
  shift
done

if [ "${LOG_FILENAME}" == "" ] ; then echo "log-atrest: logfile must be specified"; exit 9 ; fi
if [ ! -f "${LOGDIR}${LOG_FILENAME}" ] ;  then echo "log-atrest: cannot fine logfile '${LOG_FILENAME}'" ; exit 9 ; fi

POSITIONS="$(${LOGPOSITIONS} ${LOG_FILENAME})"
POSITIONCOUNT=$(${GREP} -c '^' <<_< "${POSITIONS}")

if [ ${POSITIONCOUNT} -eq 1 ] ; then
  if [ ${OPTION_VERBOSE} ] ; then echo "yes" ; fi
  exit 0
else
  if [ ${OPTION_VERBOSE} ] ; then echo "no" ; fi
  exit 1
fi
