#!/bin/bash
#
# NAME
#   log-atrest - check a log file and report if vessel was at rest.
#
# SYNOPSIS
#   log-atrest [logfile]
#   log-atrest -h
#
# DESCRIPTION
#   If the script is invoked with no arguments, then it will operate as
#   if it had been called with a single logfile argument set to the
#   value YYYYMMDD that represents the current day.
#
#   Exits with EXITVALUE = 0 if the log file indicates that the vessel
#   was at rest (i.e. did not navigate) on the day in question,
#   otherwise sets EXITVALUE = 1. The script prints "1" on STDOUT if at
#   rest, otherwise "0" (yes, I know - a trap for the unwary).
#
#   The following options are understood:
#
#   -h  print this documentation;
#
# AUTHOR
#   Paul Reeve <preeve@pdjr.eu>

. /usr/local/bin/log.defs

OPTION_VERBOSE=0
LOG_FILENAME=$( ${DATE} '+%Y%m%d' )

while  [ "${1}" != "" ] ; do
  case ${1} in
    -h)
      ${SED} -e '/^$/,$d' ${0}
      exit 0
      ;;
    -v)
      OPTION_VERBOSE=1
      ;;
    *)
      LOG_FILENAME=${1}
      ;;
  esac
  shift
done

if [ ! -f "${LOGDIR}${LOG_FILENAME}" ] ;  then echo "log-atrest: cannot find logfile '${LOG_FILENAME}'" ; exit 9 ; fi

readarray -t POSITIONS < <( ${LOGPOSITIONS} ${LOG_FILENAME} )
POSITIONCOUNT=${#POSITIONS[@]}

EXITCODE=0
if [ ${POSITIONCOUNT} -gt 1 ] ; then
  STARTPOSITION=${POSITIONS[0]}
  STARTLON=$( printf "%.4f" $(echo ${STARTPOSITION} | ${JQ} -j '.longitude') )
  STARTLAT=$( printf "%.4f" $(echo ${STARTPOSITION} | ${JQ} -j '.latitude') )
  for (( i=1; i<${POSITIONCOUNT} ; i++)) ; do
    POSITION=${POSITIONS[$i]}
    POSITIONLON=$( printf "%.4f" $(echo ${POSITION} | ${JQ} -j '.longitude') )
    if [ 1 -eq $( echo "${STARTLON} != ${POSITIONLON}" | ${BC} ) ] ; then
      EXITCODE=1
      break
    fi
    POSITIONLAT=$( printf "%.4f" $(echo ${POSITION} | ${JQ} -j '.latitude') )
    if [ 1 -eq $( echo "${STARTLAT} != ${POSITIONLAT}" | ${BC} ) ] ; then
      EXITCODE=1
      break
    fi
  done 
fi

if [ ${OPTION_VERBOSE} -eq 1 ] ; then
  if [ ${EXITCODE} -eq 0 ]; then
    echo "yes"
  else
    echo "no"
  fi
fi

exit ${EXITCODE}
