#!/bin/bash
#
# NAME
#   log-atrest - check a log file an report if vessel was at rest.
#
# SYNOPSIS
#   log-atrest [-v] [logfile]
#   log-atrest -h
#
# DESCRIPTION
#   If the script is invoked with no arguments, then it will operate as
#   if it had been called with a single logfile argument set to the
#   value YYYYMMDD that represents the current day.
#
#   Exits with EXITVALUE = 0 if the log file indicates that the vessel
#   was at rest (i.e. did not navigate) on the day in question,
#   otherwise sets EXITVALUE = 1.
#
#   The following options are understood:
#
#   -h  print this documentation;
#
#   -v  As well as setting EXITVALUE, print to standard out the values
#       "yes" if the vessel was at rest and "no" if it wasn't.
#
# AUTHOR
#   Paul Reeve <preeve@pdjr.eu>

source log.defs

LOGFILENAME=$(${DATE} +%Y%m%d)

while  [ "${1}" != "" ] ; do
  case ${1} in
    -h)
      ${GREP} '^#' ${0}
      exit 0
      ;;
    -v)
      VERBOSE=1
      ;;
    *)
      LOGFILENAME=${1}
      ;;
  esac
  shift
done

POSITIONS="$(${LOGPOSITIONS} ${LOGFILENAME})"
POSITIONCOUNT=$(${GREP} -c '^' <<< "${POSITIONS}")

if [ ${POSITIONCOUNT} -eq 1 ] ; then
  if [ ${VERBOSE} ] ; then echo "yes" ; fi
  exit 0
else
  if [ ${VERBOSE} ] ; then echo "no" ; fi
  exit 1
fi
