#!/bin/bash

LOG_SOURCE_DIRECTORY=log/
WORDPRESS_SOURCE_DIRECTORY=wordpress/

SYMBOLIC=
TARGET_DIRECTORY=
UNINSTALL_SCRIPT="/usr/local/bin/log-uninstall"

if [ "${1}" == "" ] ; then
  echo "usage: install [-s] ( log_directory | wordpress_directory )"
  exit 1
fi

while [ "${1}" != "" ] ; do
  case ${1} in
    -s)
      SYMBOLIC=yes
      echo "install: installing by symbolic link"
      ;;
    *)
      TARGET_DIRECTORY="${1}"
      ;;
  esac
done

if [ "${TARGET_DIRECTORY}" == "" ] ; then
  echo "install: log directory or WordPress directory must be specified"
  exit 1
fi

# Determine installation type
if [ -f "${TARGET_DIRECTORY}/wp-config.php" ] ; then
  SOURCE_DIRECTORY=${WORDPRESS_SOURCE_DIRECTORY}
else
  SOURCE_DIRECTORY=${LOG_SOURCE_DIRECTORY}
  DATA_DIRECTORY="${TARGET_DIRECTORY}"
  TARGET_DIRECTORY="/"
  if [ ! -f "${DATA_DIRECTORY}" ] ; then
    if [ ! -d "${DATA_DIRECTORY}" ] ; then
      mkdir -p "${DATA_DIRECTORY}"
      chmod 777 "${DATA_DIRECTORY}"
    fi
  else
    echo "install: log directory cannot be created because a file with the specified name already exists"
    exit 1
  fi
fi

rm "${UNINSTALL_SCRIPT}"
echo "#!/bin/bash" > "${UNINSTALL_SCRIPT}"
chmod 755 "${UNINSTALL_SCRIPT}"
    
if [ -d "${SOURCE_DIRECTORY}" ] ; then
  cd "${SOURCE_DIRECTORY}"
  for INSTALL_DIR_PATTERN in * ; do
    INSTALL_DIR="${TARGET_DIRECTORY}${INSTALL_DIR_PATTERN//\.//}"
    pushd "${INSTALL_DIR_PATTERN}" > /dev/null
    for SCRIPT_NAME in * ; do
      SCRIPT_PATHNAME=$( realpath ${SCRIPT_NAME} )
      pushd "${INSTALL_DIR}" > /dev/null
      rm -f ${SCRIPT_NAME}
      echo "rm \"${INSTALL_DIR}${SCRIPT_NAME}\"" >> "${UNINSTALL_SCRIPT}"
      if [ "${SYMBOLIC}" == "yes" ] ; then
        ln -s "${SCRIPT_PATHNAME}" .
      else
        cp "${SCRIPT_PATHNAME}" .
      fi
      chmod 755 "${SCRIPT_NAME}"
      popd > /dev/null
    done
    popd > /dev/null
  done
fi

echo "rm \"${UNINSTALL_SCRIPT}\"" >> "${UNINSTALL_SCRIPT}"

